#!/bin/csh -f
#
# Given an ICT with a flight path, sample GEOS-products of interest.
#

set rc = ../RC
set sampler = $ESMADIR/`uname`/bin/trj_sampler.py
set esampler = $ESMADIR/`uname`/bin/ext_sampler.py
set dest = /home/adasilva/iesa/ORACLES/sampled/plan


if ( $#argv < 1 ) then
   echo "usage:    $0 [-r n] fltplan_dc8_20160503.ict  [fcst_DTG]"
   echo "          where n is the revision number; default is 0 for R0"  
   echo "examples: $0 fltplan_dc8_20160503.ict  "
   echo "          $0 fltplan_dc8_20160503.ict  20160502_12"
   exit 1
else 

if ( "$1" == "-r" ) then
     set RN = R$2
     shift
     shift
else
     set RN = R0
endif

if ( $#argv == 2 ) then
    set ict  = $1
    set DTG  = $2
    foreach prod ( CHEM METEO )
        cp $rc/trj.fcast2.$prod.rc  /tmp/trj.fcast.$prod.$$.rc
	repl DTG $DTG /tmp/trj.fcast.$prod.$$.rc
    end
else
    set ict = $1
    foreach prod ( CHEM METEO )
       cp $rc/trj.fcast.$prod.rc  /tmp/trj.fcast.$prod.$$.rc
    end
endif

endif


        
foreach prod ( CHEM METEO )  

   set basen = `basename $ict`
   set date = `echo $basen:r | awk -F_ '{print $3}'`
   set loc = `echo $basen | awk -F_ '{print toupper($2)}'`
   set nc = $dest/ORACLES-GEOS5-$prod-${loc}_PLAN_${date}_$RN.nc

   $sampler -f NETCDF3_CLASSIC  -I -v \
             -r /tmp/trj.fcast.$prod.$$.rc -o $nc $ict

    rm -rf /tmp/trj.fcast.$prod.$$.rc*
             
end

