# config_seac4rs.yaml
campaign: "FIREXAQ"
exp_id: "e5303_m21c_jan18"
output_dir: "/discover/nobackup/projects/gmao/iesa/aerosol/campaigns/FIREX-AQ/sampled"
tmp_dir: "/discover/nobackup/acollow/temp_regrid"
merra2_archive: "/discover/nobackup/projects/gmao/merra2/data/products/MERRA2_all"
merra21c_archive: "/discover/nobackup/projects/gmao/merra21c/archive"
obs_dir: "/discover/nobackup/projects/gmao/iesa/aerosol/campaigns/FIREX-AQ/archive/DC8/HAIR.JOHNATHAN"

# Observation file naming parameters
instrument: "DIAL"
plane: "DC8"
obs_revision: "R0"

# AOP Settings
wavelengths: [532, 1064]
aop_config_m2: "/discover/nobackup/acollow/GMAOpyobs/src/config/m2_pm25.yaml"
aop_config_m21c: "/discover/nobackup/acollow/GMAOpyobs/src/config/g2g.yaml"

# Flight dates
flight_dates:
  - "20190724"
  - "20190725"
  - "20190729"
  - "20190730"
  - "20190802"
  - "20190803"
  - "20190806"
  - "20190807"
  - "20190808"
  - "20190812"
  - "20190813"
  - "20190815"
  - "20190816"
  - "20190819"
  - "20190821"
  - "20190823"
  - "20190826"
  - "20190829"
  - "20190830"
  - "20190831"
  - "20190903"
  - "20190905"
