#!/usr/bin/env python3

"""
    wrapper to concatenate files generated by sbg_vlidort.py
"""

import os
import subprocess
import shutil
from   datetime        import datetime, timedelta
from   dateutil.parser import parse         as isoparser
import argparse
import numpy as np
import time
from   MAPL.config     import Config
from   glob import glob
from netCDF4 import Dataset
import xarray as xr

class WORKSPACE(object):
    """ Create slurm scripts for running run_imager_sampler.py """
    def __init__(self,args):

        self.Date      = isoparser(args.iso_t1)
        self.enddate   = isoparser(args.iso_t2)
        self.dti       = timedelta(minutes=args.dti_mins)

        self.track_pcf   = args.track_pcf
        self.orbit_pcf   = args.orbit_pcf
        self.inst_pcf    = args.inst_pcf
        
        # get number of channels
        cf        = Config(args.inst_pcf,delim=' = ')
        chs       = cf('channels')
        chs       = np.array(chs.split(':')).astype(int)
        self.nch  = int(1 + (chs[1]-chs[0])/chs[2])

        # get filename template
        cf             = Config(args.track_pcf,delim=' = ')
        self.outTemplate    = cf('outDir')    + '/' + cf('outFile')

        # get orbit name
        cf             = Config(args.orbit_pcf,delim=' = ')
        self.orbitname      = cf('orbitname')
        self.ORBITNAME      = self.orbitname.upper()

        # get instrument name
        cf             = Config(args.inst_pcf,delim=' = ')
        self.instname       = cf('instname')

        # concat by channel
        self.concat_by_ch()


    def concat_by_ch(self):
        sdate = self.Date
        self.ch_outfiles = []
        while sdate < self.enddate:
            nymd  = str(sdate.date()).replace('-','')
            year  = str(sdate.year)
            month = str(sdate.month).zfill(2)
            day   = str(sdate.day).zfill(2)
            hour  = str(sdate.hour).zfill(2)
            minute = str(sdate.minute).zfill(2)

            inFile = self.outTemplate.replace('%year',year).replace('%month',month).replace('%day',day).replace('%nymd',nymd).replace('%hour',hour).replace('%minute',minute).replace('%orbitname',self.orbitname).replace('%ORBITNAME',self.ORBITNAME).replace('%instname',self.instname).replace('%band','*')

            infiles = sorted(glob(inFile))

            if len(infiles) != self.nch:
                raise ValueError('not the right number of infiles, got {}, should be {}'.format(len(infiles),self.nch))

            outFile    = self.outTemplate.replace('%year',year).replace('%month',month).replace('%day',day).replace('%nymd',nymd).replace('%hour',hour).replace('%minute',minute).replace('%orbitname',self.orbitname).replace('%ORBITNAME',self.ORBITNAME).replace('%instname',self.instname).replace('_%band','')

            # copy over first file
            shutil.copyfile(infiles[0],outFile)
            nc = Dataset(outFile,'a')

            # figure out which vars we're working with
            varlist = []
            for v in nc.variables.keys():
                if 'ch' in nc.variables[v].dimensions:
                    varlist.append(v)    

            varlist.remove("channel")
            ch = nc.variables['channel']

            # concat the along ch dimension
            for ich,infile in enumerate(infiles[1:]):
                nci = Dataset(infile)
                ch[ich+1] = ich+1
                for varname in varlist:
                    v = nci.variables[varname][:]
                    vo = nc.variables[varname]
                    dim = np.array(vo.dimensions)
                    ndim = len(dim)

                    if ndim == 3:
                        vo[:,:,ich+1] = v
                    elif ndim == 4:
                        vo[:,:,:,ich+1] = v
                nci.close()

            nc.close()

            # clean up inputs
            for infile in infiles:
                dirname = os.path.dirname(infile)
                fname = os.path.basename(infile)
                if not os.path.exists(dirname+'/ch'):
                    os.makedirs(dirname+'/ch')
                os.rename(infile,dirname+'/ch/'+fname)
            
            self.ch_outfiles.append(outFile)

            sdate += self.dti


if __name__ == '__main__':
    
    #Defaults
    dti_mins  = 1

    parser = argparse.ArgumentParser()
    parser.add_argument("iso_t1",help='starting iso time')
    parser.add_argument("iso_t2",help='ending iso time')

    parser.add_argument("track_pcf",
                        help="prep config file with track input file names")

    parser.add_argument("orbit_pcf",
                        help="prep config file with orbit variables")

    parser.add_argument("inst_pcf",
                        help="prep config file with instrument variables")

    parser.add_argument("--dti_mins", default=dti_mins, type=int,
                        help="Timestep in minutes for each input file (default=%i)"%dti_mins)

    parser.add_argument("-r", "--dryrun",action="store_true",
                        help="do a dry run (default=False).") 


    args = parser.parse_args()

    workspace = WORKSPACE(args)


