#!/bin/csh -f
#
# Given an ICT with a flight path, sample GEOS-products of interest.
#


set rc = ../RC
set sampler = $ESMADIR/`uname`/bin/trj_sampler.py
set esampler = $ESMADIR/`uname`/bin/ext_sampler.py
set dest = /home/adasilva/iesa/kaq/sampled/plan


if ( $#argv < 1 ) then
   echo "usage: $0 fltplan_dc8_20160503.ict"
   exit 1
else
    set ict = $1
endif

foreach prod ( CHEM METEO )
#foreach prod ( METEO )

   set basen = `basename $ict`
   set date = `echo $basen:r | awk -F_ '{print $3}'`
   set loc = `echo $basen | awk -F_ '{print toupper($2)}'`
   set nc = $dest/KORUSAQ-GEOS5-$prod-${loc}_PLAN_${date}_R0.nc

   $sampler -f NETCDF3_CLASSIC  -I -v -r $rc/trj.fcast2.$prod.rc -o $nc $ict

end

