#!/bin/csh -f
#
# Use stn_sampler to sample GEOS-products of interest at pre-defined
# cross-section defined as stations.     
#
# 
# Arlindo da Silva, May 2016
#.................................................................

set rc = ../RC
set sampler = $ESMADIR/`uname`/bin/stn_sampler.py
set dest = /home/adasilva/iesa/kaq/sampled/plan/xsect

    echo "IMPORTANT: this script needs testing before use"
    exit 1
    
if ( $#argv < 1 ) then
   echo "usage:    $0 [fcst_DTG]"
   echo "examples: $0 "
   echo "          $0 20160502_12"
   exit 1
else if ( $#argv == 2 ) then
    set ict  = $1
    set DTG  = $2
    foreach prod ( CHEM METEO )
        cp $rc/trj.fcast2.$prod.rc  /tmp/trj.fcast.$prod.$$.rc
	repl DTG $DTG /tmp/trj.fcast.$prod.$$.rc
    end
else
    set ict = $1
    set DTG = latest
    foreach prod ( CHEM METEO )
       cp $rc/trj.fcast.$prod.rc  /tmp/trj.fcast.$prod.$$.rc
    end
endif

set COLLS = `cat /tmp/trj.fcast.METEO.$$.rc /tmp/trj.fcast.CHEM.$$.rc | grep $DTG | awk '{print $4}'`

foreach xsectfn ( ../RC/*.csv )
   foreach collfn ( $COLLS )

    set coll = `basename $collfn:r | awk -F_ '{print $3$4}'`
    set xsect = `basename $xsectfn:r |awk -F- '{print $1 2 $2}'`
        
    set basen = `basename $ict`
    set date = `echo $basen:r | awk -F_ '{print $3}'`
    set nc = $dest/KORUSAQ-GEOS5-$coll-${xsect}_PLAN_${date}_R0.nc

    echo ""
    echo $sampler -f NETCDF3_CLASSIC -I -v -o $nc $xsectfn $collfn

  end
end
