'''
This code plots a time series of AOD from GEOS-FP and observations for a single station using the csv file generated by processaeronet.py. At the bottom of the code, the user must update the station name, time period requested, and the path to the csv file containing the data to plot.
'''

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import os

def plot_aod_timeseries(csv_file, station_name, start_date, end_date, output_dir='./'):
    print(f"Loading data from {csv_file}...")
    
    # Load the timeseries data
    df = pd.read_csv(csv_file)
    
    # Convert 'time' to datetime objects
    df['time'] = pd.to_datetime(df['time'])
    
    # Filter for the specific station and date range
    mask = (
        (df['station'] == station_name) & 
        (df['time'] >= pd.to_datetime(start_date)) & 
        (df['time'] <= pd.to_datetime(end_date) + pd.Timedelta(days=1)) # Include end of last day
    )
    stn_df = df[mask].sort_values('time')
    
    if stn_df.empty:
        print(f"No data found for station '{station_name}' between {start_date} and {end_date}.")
        return

    # Split data by observation type for markers
    solar_df = stn_df[stn_df['obs_type'] == 'solar']
    lunar_df = stn_df[stn_df['obs_type'] == 'lunar']

    # Initialize the plot
    fig, ax = plt.subplots(figsize=(14, 6))

    # 1. Plot Connecting lines (thin, to show time series progression without distracting from markers)
    ax.plot(stn_df['time'], stn_df['aeronet_aod'], color='black', linestyle='-', linewidth=0.8, alpha=0.4, zorder=1)
    ax.plot(stn_df['time'], stn_df['model_aod'], color='red', linestyle='-', linewidth=0.8, alpha=0.4, zorder=1)

    # 2. Plot Solar Data (Circles 'o')
    ax.scatter(solar_df['time'], solar_df['aeronet_aod'], color='black', marker='o', 
               s=50, label='AERONET (Solar)', zorder=3)
    ax.scatter(solar_df['time'], solar_df['model_aod'], color='red', marker='o', 
               s=50, label='GEOS-FP (Solar)', zorder=3)

    # 3. Plot Lunar Data (Triangles '^')
    ax.scatter(lunar_df['time'], lunar_df['aeronet_aod'], color='black', marker='^', 
               s=60, label='AERONET (Lunar)', zorder=3)
    ax.scatter(lunar_df['time'], lunar_df['model_aod'], color='red', marker='^', 
               s=60, label='GEOS-FP (Lunar)', zorder=3)

    # Formatting and labels
    ax.set_title(f"AOD (550 nm) at {station_name}", fontsize=15, fontweight='bold', pad=15)
    ax.set_xlabel("Date", fontsize=12, fontweight='bold')
    ax.set_ylabel("Aerosol Optical Depth", fontsize=12, fontweight='bold')

    # Format the X-axis for dates nicely
    ax.xaxis.set_major_locator(mdates.DayLocator(interval=7))  # Tick every 7 days
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d, %Y'))
    ax.xaxis.set_minor_locator(mdates.DayLocator(interval=1))  # Minor tick every day
    plt.xticks(rotation=45, ha='right')

    # Styling
    ax.grid(True, linestyle='--', alpha=0.6)
    ax.legend(loc='upper left')
    
    # Adjust layout to fit legend and rotated dates
    plt.tight_layout()

    # Save the figure
    os.makedirs(output_dir, exist_ok=True)
    out_file = os.path.join(output_dir, f"{station_name}_AOD_Timeseries_{start_date}_to_{end_date}.png")
    plt.savefig(out_file, dpi=300, bbox_inches='tight')
    print(f"Plot successfully saved to: {out_file}")
    
    # Optional: Display the plot if running in an interactive environment (like Jupyter)
    plt.show()

if __name__ == "__main__":
    input_csv_file = "/gpfsm/dnb34/acollow/AeroApps/AeroApps/src/Components/modules/model_utils/post/f5430_fp/AERONETsampled/f5430_fp_aeronet_timeseries_daily_20260601_20260831.csv"
    
    station = "La_Parguera"
    start = "2026-06-01"
    end = "2026-08-31"
    
    # Make sure the file exists before attempting to plot
    if os.path.exists(input_csv_file):
        plot_aod_timeseries(
            csv_file=input_csv_file,
            station_name=station,
            start_date=start,
            end_date=end
        )
    else:
        print(f"Error: Could not find the file '{actual_csv_file}'.")
        print("Please check the file path or re-run the processing script for the JJA date range.")
