'''
This code will generate a four panel plot showing maps if AOD from AERONET stations, comparing two GEOS experiments to the observations. It uses the csv file generated by process_aeronet.py as input.
'''

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import argparse
import warnings

warnings.filterwarnings('ignore')

plt.rcParams.update({'font.size': 16})

def plot_4panel_map(df, var_name, suptitle, bias_col1, bias_col2, corr_col1, corr_col2, output_path):
    """Generates a 4-panel map for Bias and Correlation comparing x53rpy and x54."""
    fig = plt.figure(figsize=(22, 14)) 
    
    # Define projections and axes
    axes = [plt.subplot(2, 2, i, projection=ccrs.PlateCarree()) for i in range(1, 5)]
    panel_labels = [
        '(a) x0053RPY Bias', '(b) x0054 Bias', 
        '(c) x0053RPY Correlation', '(d) x0054 Correlation'
    ]
    
    # Cap extremes for bias scaling (95th percentile)
    max_bias_plot = np.percentile(np.abs(df[[bias_col1, bias_col2]].dropna().values), 99)
    
    cmaps = [plt.cm.RdBu_r, plt.cm.RdBu_r, plt.cm.viridis, plt.cm.viridis]
    vmins = [-max_bias_plot, -max_bias_plot, 0.0, 0.0]
    vmaxs = [max_bias_plot, max_bias_plot, 1.0, 1.0] # Correlation is capped at 1.0
    cols = [bias_col1, bias_col2, corr_col1, corr_col2]
    
    scatters = []
    
    for i, ax in enumerate(axes):
        ax.add_feature(cfeature.COASTLINE, linewidth=0.5)
        ax.add_feature(cfeature.BORDERS, linestyle=':', linewidth=0.5)
        ax.add_feature(cfeature.LAND, facecolor='lightgray', alpha=0.3)
        ax.set_global()
        
        sc = ax.scatter(df['Lon'], df['Lat'], c=df[cols[i]], 
                        cmap=cmaps[i], vmin=vmins[i], vmax=vmaxs[i],
                        s=80, edgecolor='k', linewidth=0.3, transform=ccrs.PlateCarree())
        scatters.append(sc)
        
        ax.set_title(panel_labels[i], fontsize=22, pad=12)
        ax.gridlines(draw_labels=False, alpha=0.2)
        
    plt.subplots_adjust(wspace=0.05, hspace=0.2)
    
    # Add Colorbars
    pos_top = axes[1].get_position()
    pos_bot = axes[3].get_position()
    
    # Bias Colorbar
    cbar_ax1 = fig.add_axes([pos_top.x1 + 0.02, pos_top.y0, 0.02, pos_top.height])
    cbar1 = plt.colorbar(scatters[1], cax=cbar_ax1)
    cbar1.set_label(f'{var_name} Bias', fontsize=20)
    cbar1.ax.tick_params(labelsize=16) 
    
    # Correlation Colorbar
    cbar_ax2 = fig.add_axes([pos_bot.x1 + 0.02, pos_bot.y0, 0.02, pos_bot.height])
    cbar2 = plt.colorbar(scatters[3], cax=cbar_ax2)
    cbar2.set_label(f'{var_name} Correlation (r)', fontsize=20)
    cbar2.ax.tick_params(labelsize=16) 
    
    fig.suptitle(f'{suptitle} ({len(df)} stations)', 
                 fontsize=26, fontweight='bold', y=0.96)
                 
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")

def plot_points_map(df, output_path):
    """Generates a single-panel map showing the number of matched data points."""
    fig = plt.figure(figsize=(14, 9))
    ax = plt.subplot(1, 1, 1, projection=ccrs.PlateCarree())
    
    ax.add_feature(cfeature.COASTLINE)
    ax.add_feature(cfeature.BORDERS, linestyle=':')
    ax.add_feature(cfeature.LAND, facecolor='lightgray', alpha=0.3)
    ax.set_global()
    
    sizes = 40 + 150 * (np.log10(df['N_Points']) - np.log10(df['N_Points'].min())) / \
            (np.log10(df['N_Points'].max()) - np.log10(df['N_Points'].min()))
            
    sc = ax.scatter(df['Lon'], df['Lat'], c=df['N_Points'], 
                    cmap='magma_r', s=sizes, edgecolor='k', linewidth=0.5, 
                    transform=ccrs.PlateCarree(), alpha=0.8)
                    
    cbar = plt.colorbar(sc, shrink=0.6, pad=0.04)
    cbar.set_label('Number of Matched Hourly Observations', fontsize=18)
    cbar.ax.tick_params(labelsize=16)
    
    ax.set_title(f'Valid AERONET vs Model Data Points\n({len(df)} stations)', 
                 fontsize=22, pad=15)
                 
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")

def plot_closeness_map(df, output_path):
    """Generates a single-panel map showing which model is closer to AERONET."""
    fig = plt.figure(figsize=(14, 9))
    ax = plt.subplot(1, 1, 1, projection=ccrs.PlateCarree())
    
    ax.add_feature(cfeature.COASTLINE)
    ax.add_feature(cfeature.BORDERS, linestyle=':')
    ax.add_feature(cfeature.LAND, facecolor='lightgray', alpha=0.3)
    ax.set_global()
    
    # Calculate symmetric bounds for the divergent colormap
    max_val = np.percentile(np.abs(df['Closeness'].dropna().values), 95)
    
    # Scatter plot for closeness
    sc = ax.scatter(df['Lon'], df['Lat'], c=df['Closeness'], 
                    cmap=plt.cm.RdBu_r, vmin=-0.05, vmax=0.05,
                    s=80, edgecolor='k', linewidth=0.5, 
                    transform=ccrs.PlateCarree(), alpha=0.9)
                    
    cbar = plt.colorbar(sc, shrink=0.6, pad=0.04)
    # Explain the metric: negative means x54 is smaller (closer), positive means x53rpy is smaller (closer)
    cbar.set_label('Closeness', fontsize=18)
    cbar.ax.tick_params(labelsize=16)
    
    ax.set_title(f'Closeness to AERONET\n Blue = x54, Red = x53rpy \n({len(df)} stations)', 
                 fontsize=22, pad=15)
                 
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")

def main(data_dir, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    
    # Define the specific paths for the two generated files
    file_x53rpy = os.path.join(data_dir, "x0053RPY_aeronet_comparison_stats_20260201_20260228.csv")
    file_x54 = os.path.join(data_dir, "x0054_aeronet_comparison_stats_20260201_20260228.csv")
    
    if not os.path.exists(file_x53rpy):
        print(f"Error: Could not find {file_x53rpy}")
        return
    if not os.path.exists(file_x54):
        print(f"Error: Could not find {file_x54}")
        return
        
    df1 = pd.read_csv(file_x53rpy)
    df2 = pd.read_csv(file_x54)
    
    # Merge the two dataframes on the station location information
    df = pd.merge(df1, df2, on=['Station', 'Lat', 'Lon'], suffixes=('_x53rpy', '_x54'))
    
    # Use the minimum number of matched points between the two runs for the points map
    df['N_Points'] = df[['N_Points_x53rpy', 'N_Points_x54']].min(axis=1)
    
    original_len = len(df)
    df = df[df['N_Points'] >= 30].copy()
    print(f"Filtered stations from {original_len} to {len(df)} (requires >= 30 points)")
    
    if len(df) == 0:
        print("Error: No stations have 50 or more data points. Exiting.")
        return
    
    # Calculate Biases 
    df['x53rpy_AOD_Bias'] = df['MODEL_AOD_Mean_x53rpy'] - df['AERONET_AOD_Mean_x53rpy']
    df['x54_AOD_Bias'] = df['MODEL_AOD_Mean_x54'] - df['AERONET_AOD_Mean_x54']
    
    # Calculate Closeness Metric: abs(x54_error) - abs(x53rpy_error)
    df['x54_abs_error'] = np.abs(df['x54_AOD_Bias'])
    df['x53rpy_abs_error'] = np.abs(df['x53rpy_AOD_Bias'])
    df['Closeness'] = df['x54_abs_error'] - df['x53rpy_abs_error']
    
    # 1. AOD 4-Panel Plot
    plot_4panel_map(df, 
                    var_name="AOD",
                    suptitle="AOD at 550 nm Evaluated Against AERONET",
                    bias_col1='x53rpy_AOD_Bias', bias_col2='x54_AOD_Bias',
                    corr_col1='MODEL_AOD_Correlation_x53rpy', corr_col2='MODEL_AOD_Correlation_x54',
                    output_path=os.path.join(output_dir, "aod_comparison_4panel.png"))
                    
    # 2. Data Points Map
    plot_points_map(df, output_path=os.path.join(output_dir, "data_points_coverage.png"))
    
    # 3. Closeness Map
    plot_closeness_map(df, output_path=os.path.join(output_dir, "aod_closeness_map.png"))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--data-dir', type=str, default="/discover/nobackup/acollow/aeroeval/x54",
                        help='Directory where the CSV files are located')
    parser.add_argument('--output-dir', type=str, default="/discover/nobackup/acollow/aeroeval/x54",
                        help='Directory to save output figures')
    args = parser.parse_args()
    
    main(args.data_dir, args.output_dir)
