'xdfopen /home/jardizzo/src/FLUID/dev/share/themes/classic_ensemble/DDF/x0034.asm_inst3d_met_p.ddf'
'set xlab off'
'set ylab off'
'set dfile 1'
'set time 00z04Jul2018'
'set grads off'
'set gxout contour'
'set csmooth off'
'set cint 4'
'set cthick 4'
'set cstyle 1'
'set clab masked'
'set clopts 31 5 0.12'
'set clskip 1'
'define a004=slp.1(z=1,e=10)'
'display a004'
