#!/usr/bin/csh
# name - setup_env.bash
# purpose -
#   This script can be "sourced" from the bash shell to set environment
#   variables and modules needed for building and running the GEOS system.
#

# Add GMAOpyobs to the path
#----------------
# setenv AERODIR /discover/nobackup/pcastell/workspace/GMAOpyobs_cartopy/GMAOpyobs
#setenv AERODIR  ${NOBACKUP}/Python/GMAOpyobs
#setenv AERODIR  ${NOBACKUP}/REPOS/AOCH/AeroApps
setenv AERODIR  ${NOBACKUP}/REPOS/AOCH/GMAOpyobs
#setenv AERODIR  /gpfsm/dnb33/sgasso/Python/GMAOpyobs
#setenv AERODIR  /home/sgasso/Python/AOCH/GMAOpyobs
# setenv AERODIR ${NOBACKUP}/workspace/AeroApps_asia_aq/AeroApps/
setenv PATH ${AERODIR}/install/bin/:${PATH}

# Set Python PATH
#-----------------
#setenv PYTHONPATH ${AERODIR}/src:${AERODIR}/install/lib/Python
setenv PYTHONPATH ${AERODIR}/install/lib/Python
#setenv PYTHONPATH ${AERODIR}/install/lib
#setenv PYTHONPATH ${AERODIR}/install/lib/Python:$PYTHONPATH

# source g5_modules
source ${AERODIR}/env@/g5_modules

# Path for shared object libraries
#------------------
#setenv LD_LIBRARY_PATH ${AERODIR}/install/lib:$LD_LIBRARY_PATH
#setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${BASEDIR}/`uname -s`/lib
