#!/usr/bin/sh
#=======================================================================
# name - setup_env.bash
# purpose -
#   This script can be "sourced" from the bash shell to set environment
#   variables and modules needed for building and running the GEOS system.
#

# Add GMAOpyobs to the path
#----------------
setenv AERODIR ${NOBACKUP}/workspace/AeroApps_asia_aq/AeroApps/
setenv PATH ${AERODIR}/install/bin/:${PATH}

# Set Python PATH
#-----------------
setenv PYTHONPATH ${AERODIR}/install/lib
setenv PYTHONPATH ${AERODIR}/install/lib/Python:$PYTHONPATH

# source g5_modules
source ${AERODIR}/env@/g5_modules

# Path for shared object libraries
#------------------
setenv LD_LIBRARY_PATH ${AERODIR}/install/lib:$LD_LIBRARY_PATH
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${BASEDIR}/`uname -s`/lib

# link over scripts and datasets needed
# -------------------

# climatology datasets
setenv climatology /discover/nobackup/pcastell/workspace/aero_work/asia-aq/climatology
foreach fname (${climatology}/*20*nc)
  set basename=`basename $fname`
  if ( ! -l $basename )  then
    ln -s $fname .
  endif
end

# links to fp and MERRA2 data
set files=(${climatology}/fp ${climatology}/MERRA2_all)
foreach fname (${files})
  set basename=`basename $fname`
  if ( ! -l $basename )  then
    ln -s $fname .
  endif
end

# link over scripts
# -----------------
foreach fname (${AERODIR}/install/bin/missions/ASIAAQ/ts_plotting/*py)
  set basename=`basename $fname`
  if ( ! -l $basename )  then
    ln -s $fname .
  endif
end

# copy over input csv
# -------------------
foreach fname (${AERODIR}/install/bin/missions/ASIAAQ/ts_plotting/*csv)
  set basename=`basename $fname`
  if ( ! -f $basename )  then
    cp $fname .
  endif
end


