#!/bin/tcsh -f

set sourced=($_)
set cwd = `pwd`

if ("$sourced" != "") then
  set dir = `dirname $sourced[2]`
else
  set dir = `dirname $0`
endif

alias firexaq 'cd /discover/nobackup/projects/gmao/nca/FIREX-AQ'
